### ISSUE TITLE
Firefox rather than PhantomJS

### ISSUE THREAD

**Issue by ghost** [uhmanoa/SuggestionBox#2]
At http://courses.ics.hawaii.edu/ReviewICS314/morea/templates/reading-htmlunit-phantomjs.html
you wrote "I don’t recommend Firefox. For now, stick with HTMLUNIT or PhantomJS. If you have a use case for which Firefox makes the most sense, please let me know, I’d be interested to hear it."

Many web servers blacklist PhantomJS browsers because they associate that browser with hacking and not "legitimate" usage.  Isn't this a good reason to use Firefox?

**Comment by philipmjohnson** [comment]
Thanks for your comment. The Play Framework provides its own web server which (at the time of writing of the referenced page) did not blacklist phantomjs. So this isn't an issue in practice.

That said, this web page was written several years ago, so things might well have changed since then.  Maybe Firefox is a now a reasonable alternative. I've moved on to Meteor so I am not current with Play.
